name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v7
      - uses: jetify-com/devbox-install-action@v0.13.0
        with:
          enable-cache: true
      - name: Test
        run: devbox run -- task test
      - name: Publish coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v6.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
      - name: Lint
        run: devbox run -- task lint
